function tags = AMIGO_tags
% create tags for checks.
% add new tags for the list. 


tags = cellstr(char('#MISSING',...  % missing documentation, options etc. 
    '#PE',...       % for parameter estimation
    '#Sim',...      % for simulation i.e. SData, SObs, SModel, LRank etc. (all)
    '#Sens',...     % for sensitivity calculation (PE with gradient based local, FIM, LRank, RIdent)
    '#Cont',...
    '#DO',...
    '#FIM',...
    '#GRank',...
    '#LIdent',...
    '#LRank',...
    '#OED',...
    '#PEPostAn',...
    '#RIdent',...
    '#SData',...
    '#SObs',...
    '#SModel',...
    '#REG'));