/* mng.f -- translated by f2c (version 20100827).
   You must link the resulting object file with libf2c:
	on Microsoft Windows system, link with libf2c.lib;
	on Linux or Unix systems, link with .../path/to/libf2c.a -lm
	or, if you install libf2c.a in a standard place, with -lf2c -lm
	-- in that order, at the end of the command line, as in
		cc *.o -lf2c -lm
	Source for libf2c is in /netlib/f2c/libf2c.zip, e.g.,

		http://www.netlib.org/f2c/libf2c.zip
*/

#include "f2c.h"

/* Table of constant values */

static integer c__2 = 2;

/* Subroutine */ int mng_(integer *n, real *d__, real *x, S_fp calcf, S_fp 
	calcg, integer *iv, integer *liv, integer *lv, real *v, integer *
	uiparm, real *urparm, U_fp ufparm)
{
    /* System generated locals */
    integer i__1;

    /* Local variables */
    static real f;
    static integer g1, nf, iv1;
    extern /* Subroutine */ int rmng_(real *, real *, real *, integer *, 
	    integer *, integer *, integer *, real *, real *), ivset_(integer *
	    , integer *, integer *, integer *, real *);


/*  ***  MINIMIZE GENERAL UNCONSTRAINED OBJECTIVE FUNCTION USING   *** */
/*  ***  ANALYTIC GRADIENT AND HESSIAN APPROX. FROM SECANT UPDATE  *** */

/*     DIMENSION V(71 + N*(N+15)/2), UIPARM(*), URPARM(*) */

/*  ***  PURPOSE  *** */

/*        THIS ROUTINE INTERACTS WITH SUBROUTINE   RMNG  IN AN ATTEMPT */
/*     TO FIND AN N-VECTOR  X*  THAT MINIMIZES THE (UNCONSTRAINED) */
/*     OBJECTIVE FUNCTION COMPUTED BY  CALCF.  (OFTEN THE  X*  FOUND IS */
/*     A LOCAL MINIMIZER RATHER THAN A GLOBAL ONE.) */

/* --------------------------  PARAMETER USAGE  -------------------------- */

/* N........ (INPUT) THE NUMBER OF VARIABLES ON WHICH  F  DEPENDS, I.E., */
/*                  THE NUMBER OF COMPONENTS IN  X. */
/* D........ (INPUT/OUTPUT) A SCALE VECTOR SUCH THAT  D(I)*X(I), */
/*                  I = 1,2,...,N,  ARE ALL IN COMPARABLE UNITS. */
/*                  D CAN STRONGLY AFFECT THE BEHAVIOR OF   MNG. */
/*                  FINDING THE BEST CHOICE OF D IS GENERALLY A TRIAL- */
/*                  AND-ERROR PROCESS.  CHOOSING D SO THAT D(I)*X(I) */
/*                  HAS ABOUT THE SAME VALUE FOR ALL I OFTEN WORKS WELL. */
/*                  THE DEFAULTS PROVIDED BY SUBROUTINE IVSET (SEE IV */
/*                  BELOW) REQUIRE THE CALLER TO SUPPLY D. */
/* X........ (INPUT/OUTPUT) BEFORE (INITIALLY) CALLING   MNG, THE CALL- */
/*                  ER SHOULD SET  X  TO AN INITIAL GUESS AT  X*.  WHEN */
/*                    MNG RETURNS,  X  CONTAINS THE BEST POINT SO FAR */
/*                  FOUND, I.E., THE ONE THAT GIVES THE LEAST VALUE SO */
/*                  FAR SEEN FOR  F(X). */
/* CALCF.... (INPUT) A SUBROUTINE THAT, GIVEN X, COMPUTES F(X).  CALCF */
/*                  MUST BE DECLARED EXTERNAL IN THE CALLING PROGRAM. */
/*                  IT IS INVOKED BY */
/*                       CALL CALCF(N, X, NF, F, UIPARM, URPARM, UFPARM) */
/*                  WHEN CALCF IS CALLED, NF IS THE INVOCATION */
/*                  COUNT FOR CALCF.  NF IS INCLUDED FOR POSSIBLE USE */
/*                  WITH CALCG.  IF X IS OUT OF BOUNDS (E.G., IF IT */
/*                  WOULD CAUSE OVERFLOW IN COMPUTING F(X)), THEN CALCF */
/*                  SHOULD SET NF TO 0.  THIS WILL CAUSE A SHORTER STEP */
/*                  TO BE ATTEMPTED.  (IF X IS IN BOUNDS, THEN CALCF */
/*                  SHOULD NOT CHANGE NF.)  THE OTHER PARAMETERS ARE AS */
/*                  DESCRIBED ABOVE AND BELOW.  CALCF SHOULD NOT CHANGE */
/*                  N, P, OR X. */
/* CALCG.... (INPUT) A SUBROUTINE THAT, GIVEN X, COMPUTES G(X), THE GRA- */
/*                  DIENT OF F AT X.  CALCG MUST BE DECLARED EXTERNAL IN */
/*                  THE CALLING PROGRAM.  IT IS INVOKED BY */
/*                       CALL CALCG(N, X, NF, G, UIPARM, URPARM, UFAPRM) */
/*                  WHEN CALCG IS CALLED, NF IS THE INVOCATION */
/*                  COUNT FOR CALCF AT THE TIME F(X) WAS EVALUATED.  THE */
/*                  X PASSED TO CALCG IS USUALLY THE ONE PASSED TO CALCF */
/*                  ON EITHER ITS MOST RECENT INVOCATION OR THE ONE */
/*                  PRIOR TO IT.  IF CALCF SAVES INTERMEDIATE RESULTS */
/*                  FOR USE BY CALCG, THEN IT IS POSSIBLE TO TELL FROM */
/*                  NF WHETHER THEY ARE VALID FOR THE CURRENT X (OR */
/*                  WHICH COPY IS VALID IF TWO COPIES ARE KEPT).  IF G */
/*                  CANNOT BE COMPUTED AT X, THEN CALCG SHOULD SET NF TO */
/*                  0.  IN THIS CASE,   MNG WILL RETURN WITH IV(1) = 65. */
/*                  (IF G CAN BE COMPUTED AT X, THEN CALCG SHOULD NOT */
/*                  CHANGED NF.)  THE OTHER PARAMETERS TO CALCG ARE AS */
/*                  DESCRIBED ABOVE AND BELOW.  CALCG SHOULD NOT CHANGE */
/*                  N OR X. */
/* IV....... (INPUT/OUTPUT) AN INTEGER VALUE ARRAY OF LENGTH LIV (SEE */
/*                  BELOW) THAT HELPS CONTROL THE   MNG ALGORITHM AND */
/*                  THAT IS USED TO STORE VARIOUS INTERMEDIATE QUANTI- */
/*                  TIES.  OF PARTICULAR INTEREST ARE THE INITIALIZATION/ */
/*                  RETURN CODE IV(1) AND THE ENTRIES IN IV THAT CONTROL */
/*                  PRINTING AND LIMIT THE NUMBER OF ITERATIONS AND FUNC- */
/*                  TION EVALUATIONS.  SEE THE SECTION ON IV INPUT */
/*                  VALUES BELOW. */
/* LIV...... (INPUT) LENGTH OF IV ARRAY.  MUST BE AT LEAST 60.  IF LIV */
/*                  IS TOO SMALL, THEN   MNG RETURNS WITH IV(1) = 15. */
/*                  WHEN   MNG RETURNS, THE SMALLEST ALLOWED VALUE OF */
/*                  LIV IS STORED IN IV(LASTIV) -- SEE THE SECTION ON */
/*                  IV OUTPUT VALUES BELOW.  (THIS IS INTENDED FOR USE */
/*                  WITH EXTENSIONS OF   MNG THAT HANDLE CONSTRAINTS.) */
/* LV....... (INPUT) LENGTH OF V ARRAY.  MUST BE AT LEAST 71+N*(N+15)/2. */
/*                  (AT LEAST 77+N*(N+17)/2 FOR   MNF, AT LEAST */
/*                  78+N*(N+12) FOR   MNH).  IF LV IS TOO SMALL, THEN */
/*                    MNG RETURNS WITH IV(1) = 16.  WHEN   MNG RETURNS, */
/*                  THE SMALLEST ALLOWED VALUE OF LV IS STORED IN */
/*                  IV(LASTV) -- SEE THE SECTION ON IV OUTPUT VALUES */
/*                  BELOW. */
/* V........ (INPUT/OUTPUT) A FLOATING-POINT VALUE ARRAY OF LENGTH LV */
/*                  (SEE BELOW) THAT HELPS CONTROL THE   MNG ALGORITHM */
/*                  AND THAT IS USED TO STORE VARIOUS INTERMEDIATE */
/*                  QUANTITIES.  OF PARTICULAR INTEREST ARE THE ENTRIES */
/*                  IN V THAT LIMIT THE LENGTH OF THE FIRST STEP */
/*                  ATTEMPTED (LMAX0) AND SPECIFY CONVERGENCE TOLERANCES */
/*                  (AFCTOL, LMAXS, RFCTOL, SCTOL, XCTOL, XFTOL). */
/* UIPARM... (INPUT) USER INTEGER PARAMETER ARRAY PASSED WITHOUT CHANGE */
/*                  TO CALCF AND CALCG. */
/* URPARM... (INPUT) USER FLOATING-POINT PARAMETER ARRAY PASSED WITHOUT */
/*                  CHANGE TO CALCF AND CALCG. */
/* UFPARM... (INPUT) USER EXTERNAL SUBROUTINE OR FUNCTION PASSED WITHOUT */
/*                  CHANGE TO CALCF AND CALCG. */

/*  ***  IV INPUT VALUES (FROM SUBROUTINE IVSET)  *** */

/* IV(1)...  ON INPUT, IV(1) SHOULD HAVE A VALUE BETWEEN 0 AND 14...... */
/*             0 AND 12 MEAN THIS IS A FRESH START.  0 MEANS THAT */
/*                  IVSET(2, IV, LIV, LV, V) */
/*             IS TO BE CALLED TO PROVIDE ALL DEFAULT VALUES TO IV AND */
/*             V.  12 (THE VALUE THAT IVSET ASSIGNS TO IV(1)) MEANS THE */
/*             CALLER HAS ALREADY CALLED IVSET AND HAS POSSIBLY CHANGED */
/*             SOME IV AND/OR V ENTRIES TO NON-DEFAULT VALUES. */
/*             13 MEANS IVSET HAS BEEN CALLED AND THAT   MNG (AND */
/*              RMNG) SHOULD ONLY DO THEIR STORAGE ALLOCATION.  THAT IS, */
/*             THEY SHOULD SET THE OUTPUT COMPONENTS OF IV THAT TELL */
/*             WHERE VARIOUS SUBARRAYS ARRAYS OF V BEGIN, SUCH AS IV(G) */
/*             (AND, FOR   MNH AND  RMNH ONLY, IV(DTOL)), AND RETURN. */
/*             14 MEANS THAT A STORAGE HAS BEEN ALLOCATED (BY A CALL */
/*             WITH IV(1) = 13) AND THAT THE ALGORITHM SHOULD BE */
/*             STARTED.  WHEN CALLED WITH IV(1) = 13,   MNG RETURNS */
/*             IV(1) = 14 UNLESS LIV OR LV IS TOO SMALL (OR N IS NOT */
/*             POSITIVE).  DEFAULT = 12. */
/* IV(INITH).... IV(25) TELLS WHETHER THE HESSIAN APPROXIMATION H SHOULD */
/*             BE INITIALIZED.  1 (THE DEFAULT) MEANS  RMNG SHOULD */
/*             INITIALIZE H TO THE DIAGONAL MATRIX WHOSE I-TH DIAGONAL */
/*             ELEMENT IS D(I)**2.  0 MEANS THE CALLER HAS SUPPLIED A */
/*             CHOLESKY FACTOR  L  OF THE INITIAL HESSIAN APPROXIMATION */
/*             H = L*(L**T)  IN V, STARTING AT V(IV(LMAT)) = V(IV(42)) */
/*             (AND STORED COMPACTLY BY ROWS).  NOTE THAT IV(LMAT) MAY */
/*             BE INITIALIZED BY CALLING   MNG WITH IV(1) = 13 (SEE */
/*             THE IV(1) DISCUSSION ABOVE).  DEFAULT = 1. */
/* IV(MXFCAL)... IV(17) GIVES THE MAXIMUM NUMBER OF FUNCTION EVALUATIONS */
/*             (CALLS ON CALCF) ALLOWED.  IF THIS NUMBER DOES NOT SUF- */
/*             FICE, THEN   MNG RETURNS WITH IV(1) = 9.  DEFAULT = 200. */
/* IV(MXITER)... IV(18) GIVES THE MAXIMUM NUMBER OF ITERATIONS ALLOWED. */
/*             IT ALSO INDIRECTLY LIMITS THE NUMBER OF GRADIENT EVALUA- */
/*             TIONS (CALLS ON CALCG) TO IV(MXITER) + 1.  IF IV(MXITER) */
/*             ITERATIONS DO NOT SUFFICE, THEN   MNG RETURNS WITH */
/*             IV(1) = 10.  DEFAULT = 150. */
/* IV(OUTLEV)... IV(19) CONTROLS THE NUMBER AND LENGTH OF ITERATION SUM- */
/*             MARY LINES PRINTED (BY ITSUM).  IV(OUTLEV) = 0 MEANS DO */
/*             NOT PRINT ANY SUMMARY LINES.  OTHERWISE, PRINT A SUMMARY */
/*             LINE AFTER EACH ABS(IV(OUTLEV)) ITERATIONS.  IF IV(OUTLEV) */
/*             IS POSITIVE, THEN SUMMARY LINES OF LENGTH 78 (PLUS CARRI- */
/*             AGE CONTROL) ARE PRINTED, INCLUDING THE FOLLOWING...  THE */
/*             ITERATION AND FUNCTION EVALUATION COUNTS, F = THE CURRENT */
/*             FUNCTION VALUE, RELATIVE DIFFERENCE IN FUNCTION VALUES */
/*             ACHIEVED BY THE LATEST STEP (I.E., RELDF = (F0-V(F))/F01, */
/*             WHERE F01 IS THE MAXIMUM OF ABS(V(F)) AND ABS(V(F0)) AND */
/*             V(F0) IS THE FUNCTION VALUE FROM THE PREVIOUS ITERA- */
/*             TION), THE RELATIVE FUNCTION REDUCTION PREDICTED FOR THE */
/*             STEP JUST TAKEN (I.E., PRELDF = V(PREDUC) / F01, WHERE */
/*             V(PREDUC) IS DESCRIBED BELOW), THE SCALED RELATIVE CHANGE */
/*             IN X (SEE V(RELDX) BELOW), THE STEP PARAMETER FOR THE */
/*             STEP JUST TAKEN (STPPAR = 0 MEANS A FULL NEWTON STEP, */
/*             BETWEEN 0 AND 1 MEANS A RELAXED NEWTON STEP, BETWEEN 1 */
/*             AND 2 MEANS A DOUBLE DOGLEG STEP, GREATER THAN 2 MEANS */
/*             A SCALED DOWN CAUCHY STEP -- SEE SUBROUTINE DBLDOG), THE */
/*             2-NORM OF THE SCALE VECTOR D TIMES THE STEP JUST TAKEN */
/*             (SEE V(DSTNRM) BELOW), AND NPRELDF, I.E., */
/*             V(NREDUC)/F01, WHERE V(NREDUC) IS DESCRIBED BELOW -- IF */
/*             NPRELDF IS POSITIVE, THEN IT IS THE RELATIVE FUNCTION */
/*             REDUCTION PREDICTED FOR A NEWTON STEP (ONE WITH */
/*             STPPAR = 0).  IF NPRELDF IS NEGATIVE, THEN IT IS THE */
/*             NEGATIVE OF THE RELATIVE FUNCTION REDUCTION PREDICTED */
/*             FOR A STEP COMPUTED WITH STEP BOUND V(LMAXS) FOR USE IN */
/*             TESTING FOR SINGULAR CONVERGENCE. */
/*                  IF IV(OUTLEV) IS NEGATIVE, THEN LINES OF LENGTH 50 */
/*             ARE PRINTED, INCLUDING ONLY THE FIRST 6 ITEMS LISTED */
/*             ABOVE (THROUGH RELDX). */
/*             DEFAULT = 1. */
/* IV(PARPRT)... IV(20) = 1 MEANS PRINT ANY NONDEFAULT V VALUES ON A */
/*             FRESH START OR ANY CHANGED V VALUES ON A RESTART. */
/*             IV(PARPRT) = 0 MEANS SKIP THIS PRINTING.  DEFAULT = 1. */
/* IV(PRUNIT)... IV(21) IS THE OUTPUT UNIT NUMBER ON WHICH ALL PRINTING */
/*             IS DONE.  IV(PRUNIT) = 0 MEANS SUPPRESS ALL PRINTING. */
/*             DEFAULT = STANDARD OUTPUT UNIT (UNIT 6 ON MOST SYSTEMS). */
/* IV(SOLPRT)... IV(22) = 1 MEANS PRINT OUT THE VALUE OF X RETURNED (AS */
/*             WELL AS THE GRADIENT AND THE SCALE VECTOR D). */
/*             IV(SOLPRT) = 0 MEANS SKIP THIS PRINTING.  DEFAULT = 1. */
/* IV(STATPR)... IV(23) = 1 MEANS PRINT SUMMARY STATISTICS UPON RETURN- */
/*             ING.  THESE CONSIST OF THE FUNCTION VALUE, THE SCALED */
/*             RELATIVE CHANGE IN X CAUSED BY THE MOST RECENT STEP (SEE */
/*             V(RELDX) BELOW), THE NUMBER OF FUNCTION AND GRADIENT */
/*             EVALUATIONS (CALLS ON CALCF AND CALCG), AND THE RELATIVE */
/*             FUNCTION REDUCTIONS PREDICTED FOR THE LAST STEP TAKEN AND */
/*             FOR A NEWTON STEP (OR PERHAPS A STEP BOUNDED BY V(LMAXS) */
/*             -- SEE THE DESCRIPTIONS OF PRELDF AND NPRELDF UNDER */
/*             IV(OUTLEV) ABOVE). */
/*             IV(STATPR) = 0 MEANS SKIP THIS PRINTING. */
/*             IV(STATPR) = -1 MEANS SKIP THIS PRINTING AS WELL AS THAT */
/*             OF THE ONE-LINE TERMINATION REASON MESSAGE.  DEFAULT = 1. */
/* IV(X0PRT).... IV(24) = 1 MEANS PRINT THE INITIAL X AND SCALE VECTOR D */
/*             (ON A FRESH START ONLY).  IV(X0PRT) = 0 MEANS SKIP THIS */
/*             PRINTING.  DEFAULT = 1. */

/*  ***  (SELECTED) IV OUTPUT VALUES  *** */

/* IV(1)........ ON OUTPUT, IV(1) IS A RETURN CODE.... */
/*             3 = X-CONVERGENCE.  THE SCALED RELATIVE DIFFERENCE (SEE */
/*                  V(RELDX)) BETWEEN THE CURRENT PARAMETER VECTOR X AND */
/*                  A LOCALLY OPTIMAL PARAMETER VECTOR IS VERY LIKELY AT */
/*                  MOST V(XCTOL). */
/*             4 = RELATIVE FUNCTION CONVERGENCE.  THE RELATIVE DIFFER- */
/*                  ENCE BETWEEN THE CURRENT FUNCTION VALUE AND ITS LO- */
/*                  CALLY OPTIMAL VALUE IS VERY LIKELY AT MOST V(RFCTOL). */
/*             5 = BOTH X- AND RELATIVE FUNCTION CONVERGENCE (I.E., THE */
/*                  CONDITIONS FOR IV(1) = 3 AND IV(1) = 4 BOTH HOLD). */
/*             6 = ABSOLUTE FUNCTION CONVERGENCE.  THE CURRENT FUNCTION */
/*                  VALUE IS AT MOST V(AFCTOL) IN ABSOLUTE VALUE. */
/*             7 = SINGULAR CONVERGENCE.  THE HESSIAN NEAR THE CURRENT */
/*                  ITERATE APPEARS TO BE SINGULAR OR NEARLY SO, AND A */
/*                  STEP OF LENGTH AT MOST V(LMAXS) IS UNLIKELY TO YIELD */
/*                  A RELATIVE FUNCTION DECREASE OF MORE THAN V(SCTOL). */
/*             8 = FALSE CONVERGENCE.  THE ITERATES APPEAR TO BE CONVERG- */
/*                  ING TO A NONCRITICAL POINT.  THIS MAY MEAN THAT THE */
/*                  CONVERGENCE TOLERANCES (V(AFCTOL), V(RFCTOL), */
/*                  V(XCTOL)) ARE TOO SMALL FOR THE ACCURACY TO WHICH */
/*                  THE FUNCTION AND GRADIENT ARE BEING COMPUTED, THAT */
/*                  THERE IS AN ERROR IN COMPUTING THE GRADIENT, OR THAT */
/*                  THE FUNCTION OR GRADIENT IS DISCONTINUOUS NEAR X. */
/*             9 = FUNCTION EVALUATION LIMIT REACHED WITHOUT OTHER CON- */
/*                  VERGENCE (SEE IV(MXFCAL)). */
/*            10 = ITERATION LIMIT REACHED WITHOUT OTHER CONVERGENCE */
/*                  (SEE IV(MXITER)). */
/*            11 = STOPX RETURNED .TRUE. (EXTERNAL INTERRUPT).  SEE THE */
/*                  USAGE NOTES BELOW. */
/*            14 = STORAGE HAS BEEN ALLOCATED (AFTER A CALL WITH */
/*                  IV(1) = 13). */
/*            17 = RESTART ATTEMPTED WITH N CHANGED. */
/*            18 = D HAS A NEGATIVE COMPONENT AND IV(DTYPE) .LE. 0. */
/*            19...43 = V(IV(1)) IS OUT OF RANGE. */
/*            63 = F(X) CANNOT BE COMPUTED AT THE INITIAL X. */
/*            64 = BAD PARAMETERS PASSED TO ASSESS (WHICH SHOULD NOT */
/*                  OCCUR). */
/*            65 = THE GRADIENT COULD NOT BE COMPUTED AT X (SEE CALCG */
/*                  ABOVE). */
/*            67 = BAD FIRST PARAMETER TO IVSET. */
/*            80 = IV(1) WAS OUT OF RANGE. */
/*            81 = N IS NOT POSITIVE. */
/* IV(G)........ IV(28) IS THE STARTING SUBSCRIPT IN V OF THE CURRENT */
/*             GRADIENT VECTOR (THE ONE CORRESPONDING TO X). */
/* IV(LASTIV)... IV(44) IS THE LEAST ACCEPTABLE VALUE OF LIV.  (IT IS */
/*             ONLY SET IF LIV IS AT LEAST 44.) */
/* IV(LASTV).... IV(45) IS THE LEAST ACCEPTABLE VALUE OF LV.  (IT IS */
/*             ONLY SET IF LIV IS LARGE ENOUGH, AT LEAST IV(LASTIV).) */
/* IV(NFCALL)... IV(6) IS THE NUMBER OF CALLS SO FAR MADE ON CALCF (I.E., */
/*             FUNCTION EVALUATIONS). */
/* IV(NGCALL)... IV(30) IS THE NUMBER OF GRADIENT EVALUATIONS (CALLS ON */
/*             CALCG). */
/* IV(NITER).... IV(31) IS THE NUMBER OF ITERATIONS PERFORMED. */

/*  ***  (SELECTED) V INPUT VALUES (FROM SUBROUTINE IVSET)  *** */

/* V(BIAS)..... V(43) IS THE BIAS PARAMETER USED IN SUBROUTINE DBLDOG -- */
/*             SEE THAT SUBROUTINE FOR DETAILS.  DEFAULT = 0.8. */
/* V(AFCTOL)... V(31) IS THE ABSOLUTE FUNCTION CONVERGENCE TOLERANCE. */
/*             IF   MNG FINDS A POINT WHERE THE FUNCTION VALUE IS LESS */
/*             THAN V(AFCTOL) IN ABSOLUTE VALUE, AND IF   MNG DOES NOT */
/*             RETURN WITH IV(1) = 3, 4, OR 5, THEN IT RETURNS WITH */
/*             IV(1) = 6.  THIS TEST CAN BE TURNED OFF BY SETTING */
/*             V(AFCTOL) TO ZERO.  DEFAULT = MAX(10**-20, MACHEP**2), */
/*             WHERE MACHEP IS THE UNIT ROUNDOFF. */
/* V(DINIT).... V(38), IF NONNEGATIVE, IS THE VALUE TO WHICH THE SCALE */
/*             VECTOR D IS INITIALIZED.  DEFAULT = -1. */
/* V(LMAX0).... V(35) GIVES THE MAXIMUM 2-NORM ALLOWED FOR D TIMES THE */
/*             VERY FIRST STEP THAT   MNG ATTEMPTS.  THIS PARAMETER CAN */
/*             MARKEDLY AFFECT THE PERFORMANCE OF   MNG. */
/* V(LMAXS).... V(36) IS USED IN TESTING FOR SINGULAR CONVERGENCE -- IF */
/*             THE FUNCTION REDUCTION PREDICTED FOR A STEP OF LENGTH */
/*             BOUNDED BY V(LMAXS) IS AT MOST V(SCTOL) * ABS(F0), WHERE */
/*             F0  IS THE FUNCTION VALUE AT THE START OF THE CURRENT */
/*             ITERATION, AND IF   MNG DOES NOT RETURN WITH IV(1) = 3, */
/*             4, 5, OR 6, THEN IT RETURNS WITH IV(1) = 7.  DEFAULT = 1. */
/* V(RFCTOL)... V(32) IS THE RELATIVE FUNCTION CONVERGENCE TOLERANCE. */
/*             IF THE CURRENT MODEL PREDICTS A MAXIMUM POSSIBLE FUNCTION */
/*             REDUCTION (SEE V(NREDUC)) OF AT MOST V(RFCTOL)*ABS(F0) */
/*             AT THE START OF THE CURRENT ITERATION, WHERE  F0  IS THE */
/*             THEN CURRENT FUNCTION VALUE, AND IF THE LAST STEP ATTEMPT- */
/*             ED ACHIEVED NO MORE THAN TWICE THE PREDICTED FUNCTION */
/*             DECREASE, THEN   MNG RETURNS WITH IV(1) = 4 (OR 5). */
/*             DEFAULT = MAX(10**-10, MACHEP**(2/3)), WHERE MACHEP IS */
/*             THE UNIT ROUNDOFF. */
/* V(SCTOL).... V(37) IS THE SINGULAR CONVERGENCE TOLERANCE -- SEE THE */
/*             DESCRIPTION OF V(LMAXS) ABOVE. */
/* V(TUNER1)... V(26) HELPS DECIDE WHEN TO CHECK FOR FALSE CONVERGENCE. */
/*             THIS IS DONE IF THE ACTUAL FUNCTION DECREASE FROM THE */
/*             CURRENT STEP IS NO MORE THAN V(TUNER1) TIMES ITS PREDICT- */
/*             ED VALUE.  DEFAULT = 0.1. */
/* V(XCTOL).... V(33) IS THE X-CONVERGENCE TOLERANCE.  IF A NEWTON STEP */
/*             (SEE V(NREDUC)) IS TRIED THAT HAS V(RELDX) .LE. V(XCTOL) */
/*             AND IF THIS STEP YIELDS AT MOST TWICE THE PREDICTED FUNC- */
/*             TION DECREASE, THEN   MNG RETURNS WITH IV(1) = 3 (OR 5). */
/*             (SEE THE DESCRIPTION OF V(RELDX) BELOW.) */
/*             DEFAULT = MACHEP**0.5, WHERE MACHEP IS THE UNIT ROUNDOFF. */
/* V(XFTOL).... V(34) IS THE FALSE CONVERGENCE TOLERANCE.  IF A STEP IS */
/*             TRIED THAT GIVES NO MORE THAN V(TUNER1) TIMES THE PREDICT- */
/*             ED FUNCTION DECREASE AND THAT HAS V(RELDX) .LE. V(XFTOL), */
/*             AND IF   MNG DOES NOT RETURN WITH IV(1) = 3, 4, 5, 6, OR */
/*             7, THEN IT RETURNS WITH IV(1) = 8.  (SEE THE DESCRIPTION */
/*             OF V(RELDX) BELOW.)  DEFAULT = 100*MACHEP, WHERE */
/*             MACHEP IS THE UNIT ROUNDOFF. */
/* V(*)........ IVSET SUPPLIES TO V A NUMBER OF TUNING CONSTANTS, WITH */
/*             WHICH IT SHOULD ORDINARILY BE UNNECESSARY TO TINKER.  SEE */
/*             SECTION 17 OF VERSION 2.2 OF THE NL2SOL USAGE SUMMARY */
/*             (I.E., THE APPENDIX TO REF. 1) FOR DETAILS ON V(I), */
/*             I = DECFAC, INCFAC, PHMNFC, PHMXFC, RDFCMN, RDFCMX, */
/*             TUNER2, TUNER3, TUNER4, TUNER5. */

/*  ***  (SELECTED) V OUTPUT VALUES  *** */

/* V(DGNORM)... V(1) IS THE 2-NORM OF (DIAG(D)**-1)*G, WHERE G IS THE */
/*             MOST RECENTLY COMPUTED GRADIENT. */
/* V(DSTNRM)... V(2) IS THE 2-NORM OF DIAG(D)*STEP, WHERE STEP IS THE */
/*             CURRENT STEP. */
/* V(F)........ V(10) IS THE CURRENT FUNCTION VALUE. */
/* V(F0)....... V(13) IS THE FUNCTION VALUE AT THE START OF THE CURRENT */
/*             ITERATION. */
/* V(NREDUC)... V(6), IF POSITIVE, IS THE MAXIMUM FUNCTION REDUCTION */
/*             POSSIBLE ACCORDING TO THE CURRENT MODEL, I.E., THE FUNC- */
/*             TION REDUCTION PREDICTED FOR A NEWTON STEP (I.E., */
/*             STEP = -H**-1 * G,  WHERE  G  IS THE CURRENT GRADIENT AND */
/*             H IS THE CURRENT HESSIAN APPROXIMATION). */
/*                  IF V(NREDUC) IS NEGATIVE, THEN IT IS THE NEGATIVE OF */
/*             THE FUNCTION REDUCTION PREDICTED FOR A STEP COMPUTED WITH */
/*             A STEP BOUND OF V(LMAXS) FOR USE IN TESTING FOR SINGULAR */
/*             CONVERGENCE. */
/* V(PREDUC)... V(7) IS THE FUNCTION REDUCTION PREDICTED (BY THE CURRENT */
/*             QUADRATIC MODEL) FOR THE CURRENT STEP.  THIS (DIVIDED BY */
/*             V(F0)) IS USED IN TESTING FOR RELATIVE FUNCTION */
/*             CONVERGENCE. */
/* V(RELDX).... V(17) IS THE SCALED RELATIVE CHANGE IN X CAUSED BY THE */
/*             CURRENT STEP, COMPUTED AS */
/*                  MAX(ABS(D(I)*(X(I)-X0(I)), 1 .LE. I .LE. P) / */
/*                     MAX(D(I)*(ABS(X(I))+ABS(X0(I))), 1 .LE. I .LE. P), */
/*             WHERE X = X0 + STEP. */

/* -------------------------------  NOTES  ------------------------------- */

/*  ***  ALGORITHM NOTES  *** */

/*        THIS ROUTINE USES A HESSIAN APPROXIMATION COMPUTED FROM THE */
/*     BFGS UPDATE (SEE REF 3).  ONLY A CHOLESKY FACTOR OF THE HESSIAN */
/*     APPROXIMATION IS STORED, AND THIS IS UPDATED USING IDEAS FROM */
/*     REF. 4.  STEPS ARE COMPUTED BY THE DOUBLE DOGLEG SCHEME DESCRIBED */
/*     IN REF. 2.  THE STEPS ARE ASSESSED AS IN REF. 1. */

/*  ***  USAGE NOTES  *** */

/*        AFTER A RETURN WITH IV(1) .LE. 11, IT IS POSSIBLE TO RESTART, */
/*     I.E., TO CHANGE SOME OF THE IV AND V INPUT VALUES DESCRIBED ABOVE */
/*     AND CONTINUE THE ALGORITHM FROM THE POINT WHERE IT WAS INTERRUPT- */
/*     ED.  IV(1) SHOULD NOT BE CHANGED, NOR SHOULD ANY ENTRIES OF IV */
/*     AND V OTHER THAN THE INPUT VALUES (THOSE SUPPLIED BY IVSET). */
/*        THOSE WHO DO NOT WISH TO WRITE A CALCG WHICH COMPUTES THE */
/*     GRADIENT ANALYTICALLY SHOULD CALL   MNF RATHER THAN   MNG. */
/*       MNF USES FINITE DIFFERENCES TO COMPUTE AN APPROXIMATE GRADIENT. */
/*        THOSE WHO WOULD PREFER TO PROVIDE F AND G (THE FUNCTION AND */
/*     GRADIENT) BY REVERSE COMMUNICATION RATHER THAN BY WRITING SUBROU- */
/*     TINES CALCF AND CALCG MAY CALL ON  RMNG DIRECTLY.  SEE THE COM- */
/*     MENTS AT THE BEGINNING OF  RMNG. */
/*        THOSE WHO USE   MNG INTERACTIVELY MAY WISH TO SUPPLY THEIR */
/*     OWN STOPX FUNCTION, WHICH SHOULD RETURN .TRUE. IF THE BREAK KEY */
/*     HAS BEEN PRESSED SINCE STOPX WAS LAST INVOKED.  THIS MAKES IT */
/*     POSSIBLE TO EXTERNALLY INTERRUPT   MNG (WHICH WILL RETURN WITH */
/*     IV(1) = 11 IF STOPX RETURNS .TRUE.). */
/*        STORAGE FOR G IS ALLOCATED AT THE END OF V.  THUS THE CALLER */
/*     MAY MAKE V LONGER THAN SPECIFIED ABOVE AND MAY ALLOW CALCG TO USE */
/*     ELEMENTS OF G BEYOND THE FIRST N AS SCRATCH STORAGE. */

/*  ***  PORTABILITY NOTES  *** */

/*        THE   MNG DISTRIBUTION TAPE CONTAINS BOTH SINGLE- AND DOUBLE- */
/*     PRECISION VERSIONS OF THE   MNG SOURCE CODE, SO IT SHOULD BE UN- */
/*     NECESSARY TO CHANGE PRECISIONS. */
/*        ONLY THE FUNCTIONS I7MDCN AND  R7MDC CONTAIN MACHINE-DEPENDENT */
/*     CONSTANTS.  TO CHANGE FROM ONE MACHINE TO ANOTHER, IT SHOULD */
/*     SUFFICE TO CHANGE THE (FEW) RELEVANT LINES IN THESE FUNCTIONS. */
/*        INTRINSIC FUNCTIONS ARE EXPLICITLY DECLARED.  ON CERTAIN COM- */
/*     PUTERS (E.G. UNIVAC), IT MAY BE NECESSARY TO COMMENT OUT THESE */
/*     DECLARATIONS.  SO THAT THIS MAY BE DONE AUTOMATICALLY BY A SIMPLE */
/*     PROGRAM, SUCH DECLARATIONS ARE PRECEDED BY A COMMENT HAVING C/+ */
/*     IN COLUMNS 1-3 AND BLANKS IN COLUMNS 4-72 AND ARE FOLLOWED BY */
/*     A COMMENT HAVING C/ IN COLUMNS 1 AND 2 AND BLANKS IN COLUMNS 3-72. */
/*        THE   MNG SOURCE CODE IS EXPRESSED IN 1966 ANSI STANDARD */
/*     FORTRAN.  IT MAY BE CONVERTED TO FORTRAN 77 BY COMMENTING OUT ALL */
/*     LINES THAT FALL BETWEEN A LINE HAVING C/6 IN COLUMNS 1-3 AND A */
/*     LINE HAVING C/7 IN COLUMNS 1-3 AND BY REMOVING (I.E., REPLACING */
/*     BY A BLANK) THE C IN COLUMN 1 OF THE LINES THAT FOLLOW THE C/7 */
/*     LINE AND PRECEDE A LINE HAVING C/ IN COLUMNS 1-2 AND BLANKS IN */
/*     COLUMNS 3-72.  THESE CHANGES CONVERT SOME DATA STATEMENTS INTO */
/*     PARAMETER STATEMENTS, CONVERT SOME VARIABLES FROM REAL TO */
/*     CHARACTER*4, AND MAKE THE DATA STATEMENTS THAT INITIALIZE THESE */
/*     VARIABLES USE CHARACTER STRINGS DELIMITED BY PRIMES INSTEAD */
/*     OF HOLLERITH CONSTANTS.  (SUCH VARIABLES AND DATA STATEMENTS */
/*     APPEAR ONLY IN MODULES ITSUM AND PARCK.  PARAMETER STATEMENTS */
/*     APPEAR NEARLY EVERYWHERE.)  THESE CHANGES ALSO ADD SAVE STATE- */
/*     MENTS FOR VARIABLES GIVEN MACHINE-DEPENDENT CONSTANTS BY  R7MDC. */

/*  ***  REFERENCES  *** */

/* 1.  DENNIS, J.E., GAY, D.M., AND WELSCH, R.E. (1981), ALGORITHM 573 -- */
/*             AN ADAPTIVE NONLINEAR LEAST-SQUARES ALGORITHM, ACM TRANS. */
/*             MATH. SOFTWARE 7, PP. 369-383. */

/* 2.  DENNIS, J.E., AND MEI, H.H.W. (1979), TWO NEW UNCONSTRAINED OPTI- */
/*             MIZATION ALGORITHMS WHICH USE FUNCTION AND GRADIENT */
/*             VALUES, J. OPTIM. THEORY APPLIC. 28, PP. 453-482. */

/* 3.  DENNIS, J.E., AND MORE, J.J. (1977), QUASI-NEWTON METHODS, MOTIVA- */
/*             TION AND THEORY, SIAM REV. 19, PP. 46-89. */

/* 4.  GOLDFARB, D. (1976), FACTORIZED VARIABLE METRIC METHODS FOR UNCON- */
/*             STRAINED OPTIMIZATION, MATH. COMPUT. 30, PP. 796-811. */

/*  ***  GENERAL  *** */

/*     CODED BY DAVID M. GAY (WINTER 1980).  REVISED SUMMER 1982. */
/*     THIS SUBROUTINE WAS WRITTEN IN CONNECTION WITH RESEARCH */
/*     SUPPORTED IN PART BY THE NATIONAL SCIENCE FOUNDATION UNDER */
/*     GRANTS MCS-7600324, DCR75-10143, 76-14311DSS, MCS76-11989, */
/*     AND MCS-7906671. */
/* . */

/* ----------------------------  DECLARATIONS  --------------------------- */


/* IVSET... SUPPLIES DEFAULT IV AND V INPUT COMPONENTS. */
/*  RMNG... REVERSE-COMMUNICATION ROUTINE THAT CARRIES OUT   MNG ALGO- */
/*             RITHM. */


/*  ***  SUBSCRIPTS FOR IV   *** */


/* /6 */
/*     DATA NEXTV/47/, NFCALL/6/, NFGCAL/7/, G/28/, TOOBIG/2/, VNEED/4/ */
/* /7 */
/* / */

/* +++++++++++++++++++++++++++++++  BODY  ++++++++++++++++++++++++++++++++ */

    /* Parameter adjustments */
    --x;
    --d__;
    --iv;
    --v;
    --uiparm;
    --urparm;

    /* Function Body */
    if (iv[1] == 0) {
	ivset_(&c__2, &iv[1], liv, lv, &v[1]);
    }
    iv1 = iv[1];
    if (iv1 == 12 || iv1 == 13) {
	iv[4] += *n;
    }
    if (iv1 == 14) {
	goto L10;
    }
    if (iv1 > 2 && iv1 < 12) {
	goto L10;
    }
    g1 = 1;
    if (iv1 == 12) {
	iv[1] = 13;
    }
    goto L20;

L10:
    g1 = iv[28];

L20:
    rmng_(&d__[1], &f, &v[g1], &iv[1], liv, lv, n, &v[1], &x[1]);
    if ((i__1 = iv[1] - 2) < 0) {
	goto L30;
    } else if (i__1 == 0) {
	goto L40;
    } else {
	goto L50;
    }

L30:
    nf = iv[6];
    (*calcf)(n, &x[1], &nf, &f, &uiparm[1], &urparm[1], (U_fp)ufparm);
    if (nf <= 0) {
	iv[2] = 1;
    }
    goto L20;

L40:
    nf = iv[7];
    (*calcg)(n, &x[1], &nf, &v[g1], &uiparm[1], &urparm[1], (U_fp)ufparm);
    if (nf <= 0) {
	iv[2] = 1;
    }
    goto L20;

L50:
    if (iv[1] != 14) {
	goto L999;
    }

/*  ***  STORAGE ALLOCATION */

    iv[28] = iv[47];
    iv[47] = iv[28] + *n;
    if (iv1 != 13) {
	goto L10;
    }

L999:
    return 0;
/*  ***  LAST CARD OF   MNG FOLLOWS  *** */
} /* mng_ */

